### ISSUE TITLE
build error even though octomap path in octomap-config.cmake is modified

### ISSUE THREAD

**Issue by robbiedood** [gaoxiang12/octomap_tutor#3]
Hope to hear your expertise on the issue.

octomap has been installed (bin/octovis octomap/share/data/geb079.bt is working) 

And follow octomap_tutor installation, change octomap path. However, still get the error:

Could not find a package configuration file provided by "octomap" with any
  of the following names:

    octomapConfig.cmake
    octomap-config.cmake

  Add the installation prefix of "octomap" to CMAKE_PREFIX_PATH or set
  "octomap_DIR" to a directory containing one of the above files.  If
  "octomap" provides a separate development package or SDK, be sure it has
  been installed.

=======================
OS is ubuntu 18.04

**Comment by lukelu520** [comment]
export CMAKE_PREFIX_PATH=path-to-octomap  
can solve the issue.
